version: '3.3'

services:
    transformer_php:
        image: dh.rinsvent.ru/php8dev
        container_name: transformer_php
        volumes:
            - ./:/app
        environment:
            USE_COMPOSER_SCRIPTS: 1
            PHP_IDE_CONFIG: "serverName=transformer_php"

networks:
    default:
        external:
            name: full-project
